options:
  log-locally:
    type: boolean
    default: false
    description: Should logs be written locally as well as forwarded?
  replication-mode:
    type: string
    default: fanout
    description: Possible options are 'fanout' or 'failover' fanout replicates the log messages over all the defined syslog relations, failover replicates the log messages just if the previous server is down. Failover always uses tcp for the protocol.
  protocol:
    type: string
    default: "udp"
    description: "transport protocol to use, currently supported options: udp, relp, tcp"
  watch-files:
    type: string
    default: "/var/log/dpkg.log /var/log/apt/history.log"
    description: "A space separated list of files to follow with rsyslog imfile and forward to the aggregator. If set to empty string no files will be watched with imfile."

