options:
  cert:
    type: string
    default: ""
    description: TLS certificate in base64 format to access rsyslog server
  log-locally:
    type: boolean
    default: false
    description: Should logs be written locally as well as forwarded?
  replication-mode:
    type: string
    default: fanout
    description: Possible options are 'fanout' or 'failover' fanout replicates the log messages over all the defined syslog relations, failover replicates the log messages just if the previous server is down. Failover always uses tcp for the protocol.
  nagios_context:
    default: "juju"
    type: string
    description: >
        Used by the nrpe-external-master subordinate charm.
        A string that will be prepended to instance name to set the host name
        in nagios. So for instance the hostname would be something like:
            juju-rsyslog-forwarder-ha-0
        If you're running multiple environments with the same services in them
        this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: >
        A comma-separated list of nagios servicegroups.
        If left empty, the nagios_context will be used as the servicegroup
  protocol:
    type: string
    default: "udp"
    description: "transport protocol to use, currently supported options: udp, relp, tcp"
  watch-files:
    type: string
    default: "/var/log/dpkg.log /var/log/apt/history.log"
    description: "A space separated list of files to follow with rsyslog imfile and forward to the aggregator. If set to empty string no files will be watched with imfile."
  forward_hosts:
    type: string
    default:
    description: >
        A comma-separated list of key=value representing hostname and 
        ip address of servers to forward all logs to as in
        hostname1=host_ip1,hostname2=host_ip2,hostname3=host_ip3
