#!/bin/bash

set -eu

juju-log 'Ensuring dependencies are installed'
apt-get install -y python python-apt python-yaml python-sqlalchemy

juju-log 'Invoking python-based install hook'
exec -a install python hooks/hooks.py
