#!/bin/sh

set -eu

juju-log 'Ensuring dependencies are installed'
apt-get install -y python3 python3-apt python3-yaml python3-sqlalchemy

juju-log 'Invoking python-based upgrade-charm hook'
python3 hooks/hooks.py upgrade-charm
